# frozen_string_literal: true

lib = File.expand_path('lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'csstats/version'

github_repo_url = 'https://github.com/jpalumickas/csstats'

Gem::Specification.new do |spec|
  spec.name = 'csstats'
  spec.version = CSstats::VERSION
  spec.author = 'Justas Palumickas'
  spec.email = 'jpalumickas@gmail.com'

  spec.summary = spec.description
  spec.description = 'Gem which handle csstats.dat file generated by CSX' \
                    ' module in AMX Mod X (http://www.amxmodx.org/)'
  spec.homepage = github_repo_url
  spec.license = 'MIT'
  spec.metadata = {
    'bug_tracker_uri' => "#{github_repo_url}/issues",
    'source_code_uri' => "#{github_repo_url}/tree/v#{CSstats::VERSION}",
    'changelog_uri' => "#{github_repo_url}/releases/tag/v#{CSstats::VERSION}"
  }

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added
  # into git.
  spec.files = Dir.chdir(File.expand_path(__dir__)) do
    `git ls-files -z`.split("\x0").reject do |f|
      f.match(%r{^(test|spec|features)/})
    end
  end
  spec.bindir        = 'exe'
  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }
  spec.require_paths = ['lib']
  spec.required_ruby_version = '>= 2.4.0'

  spec.add_dependency 'hashie', '~> 3.5'
  spec.add_development_dependency 'bundler', '~> 2.0'
end
