# coding: utf-8
lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'csstats/version'

Gem::Specification.new do |gem|
  gem.name = "CSstats"
  gem.authors = ["Justas Palumickas"]
  gem.email = ["justas@elish.lt"]
  gem.description = %q{ Gem which handle csstats.dat file generated by CSX module in AMX Mod X (http://www.amxmodx.org/) }
  gem.summary = gem.description
  gem.homepage = "https://github.com/jpalumickas/csstats/"
  gem.licenses = ['MIT']

  gem.files = `git ls-files`.split($/)
  gem.executables = gem.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
  gem.test_files = gem.files.grep(%r{^(test|spec|features)/})
  gem.require_paths = ["lib"]

  gem.add_development_dependency 'bundler', '~> 1.0'

  gem.version = CSstats::VERSION
end